# Generated by Django 5.0 on 2024-12-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprogress',
            options={'managed': True, 'verbose_name_plural': 'Training Progress'},
        ),
        migrations.AlterModelOptions(
            name='trainingoutline',
            options={'managed': True, 'verbose_name_plural': 'Training Outline'},
        ),
        migrations.AlterModelOptions(
            name='trainingstatus',
            options={'managed': True, 'verbose_name_plural': 'Training Status'},
        ),
    ]
